### ISSUE TITLE
Incorrect prices for stims on Hickes Research Outpost 

### ISSUE THREAD

**Issue by ChadMcChode** [EtienneLamoureux/sc-trade-tools#93] opened 2020-11-27 02:28 UTC
![ScreenShot0000](https://user-images.githubusercontent.com/75104441/100403929-c14e7600-3025-11eb-813c-4fe57df9f8ec.jpg)
Stims are listed on the website as selling for 2.8 UEC/unit but in-game sell for 3.05 UEC/unit

**Comment by EtienneLamoureux** [comment] 2020-11-27 13:50
Caused by:
> Why are the prices reported different from the ones in-game?
> The universe simulation makes the prices vary based on supply and demand. Since the data comes from the static game files, the tools will currently only report the most optimistic profit to be made. I hope have dynamic prices in the future.
- https://sc-trade.tools/home#faq

Will be fixed by https://github.com/EtienneLamoureux/sc-trade-tools/issues/73

**Closed** 2020-11-27 13:50 UTC
Labels: bug, duplicate
