### ISSUE TITLE
Fix the incorrect shop stocks

### ISSUE THREAD

**Issue by BIlyJohnson** [EtienneLamoureux/sc-trade-tools#80] opened 2020-09-30 10:56 UTC
## Describe the bug
I can buy much less stock than what is said on the site.

## To Reproduce
In caterpillar, make a route on the site, and do it in the game. Then impossible to buy as much as the site says.

## Expected behaviour
I would like the site to update the stocks for each trading console, so that I can see in advance if it is worth taking the route.

**Comment by EtienneLamoureux** [comment] 2020-09-30 12:23
Hi and thanks for the report! First of all, an explanation on what is happening: 

> Why can't I buy/sell as much of a commodity as the website says I can?
> As the economy is global, it is shared across all servers. If someone else is or has been buying/selling the same commodity as you, the available stock will be lowered by that much. Since the data comes from the static game files, the tools will currently only report the total inventory and refresh rates. I hope to have dynamic stock details in the future.
- https://sc-trade.tools/home#faq

I am aware of the problem and I know how frustrating it can be to arrive at a location and not be able to fill up on a commodity. Issue https://github.com/EtienneLamoureux/sc-trade-tools/issues/73 in the backlog aims to fix this, but right now CIG doesn't expose any API to allow it, so it might be a little while before it can be implemented.

I'm happy to be able to suggest some workaround for the problem though!
1. Consider using the "Show stock details" > "Minimum refresh rate" filter, [like so](https://sc-trade.tools/trade-routes?q=%257B%2522ship%2522:%2522Caterpillar%2522,%2522investment%2522:1000000,%2522isCargoStolen%2522:false,%2522profitType%2522:%2522time%2522,%2522allowableDetour%2522:25,%2522maxStops%2522:5,%2522allowWaitTimes%2522:false,%2522showDetails%2522:true,%2522minQuantityPerMinute%2522:5000,%2522itemTypesType%2522:%2522blacklist%2522,%2522itemNamesType%2522:%2522blacklist%2522,%2522locationTypesType%2522:%2522blacklist%2522,%2522locationNames%2522:%255B%255D,%2522locationNamesType%2522:%2522blacklist%2522,%2522avoidHiddenLocations%2522:true%257D), to only shop from well-stocked locations.
2. Optionally, you can also use the "Alternative commodities" button to see what else can be bought and sold for a profit on the same route. It's not as good as knowing supplies in real-time I know, but it's what I can provide at the moment :)

**Comment by EtienneLamoureux** [comment] 2020-09-30 12:24
I will keep this issue as a reference, but mark it as a duplicate of #73

**Closed by EtienneLamoureux** 2020-09-30 12:24 UTC
Labels: bug, duplicate
